### PR TITLE
Contact us now has a Form for easy Emails. Fixes issue #48

### LINKED ISSUE #48: Revamp Contact-Us Page
It is doing the bare minimum at the moment. Would be nice if there was a form in contact us.

### PR DESCRIPTION
**Pull request by aditikilledar**
closes #48

### CODE REVIEW

File: frontend/src/components/ContactUs.js [hunk 1]
```diff
@@ -1,31 +1,79 @@
...
+            margin="normal"
+            name="message"
+
+          />
+          <Button
+            type="submit"
+            variant="contained"
+            color="primary"
+            style={{ marginTop: '20px' }}
+          >
```
Comment (shashank-madan) [inline frontend/src/components/ContactUs.js:71]: Can we have the form similar to an email structure?
Fields:
Name
Email
Subject
Message/Body

**Review by shashank-madan — CHANGES_REQUESTED** [review]

File: frontend/src/components/ContactUs.js (hunk 1 above)
Comment (aditikilledar) [reply frontend/src/components/ContactUs.js:71]: I don't think adding the email is necessary. The submit button opens the default mail application, so it is obvious which email it is being sent from.

Comment (aditikilledar) [reply frontend/src/components/ContactUs.js]: I've added the subject, though. Please review!

Comment (shashank-madan) [reply frontend/src/components/ContactUs.js]: Is it possible to send the mail directly from our site? Instead of opening the mail application. That's why I thought email field would be necessary.

Comment (aditikilledar) [reply frontend/src/components/ContactUs.js]: We can possibly add that in a future scope, or explore that once we fix other issues of higher priority. But I do think we should close this for now.

**Comment by srina1h** [comment]
please create new issue for sending email directly from the site. Approving and closing this

**Review by srina1h — APPROVED** [review]
